# Generated by Django 4.2.7 on 2023-12-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aula5', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dado',
            name='cidade',
            field=models.CharField(default='Digite uma cidade', max_length=255),
        ),
        migrations.AddField(
            model_name='dado',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dado',
            name='pais_trabalho',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
