# Generated by Django 4.2.7 on 2023-12-12 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_aula5', '0002_dado_cidade_dado_data_nascimento_dado_pais_trabalho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dado',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='dado',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='dado',
            name='pais_trabalho',
        ),
    ]
