# Generated by Django 4.2.7 on 2023-12-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aula5', '0003_remove_dado_cidade_remove_dado_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dado',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dado',
            name='pais',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
